name: Sync to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and Push to GitHub
        run: |
          git clone --mirror https://git.irregularchat.com/irregulars/IrregularChatWiki.git repo
          cd repo
          git push --mirror https://${{ secrets.GH_USER }}:${{ secrets.GH_PAT }}@github.com/gitayam/IrregularChatWiki.git
